SET search_path TO ${database.defaultSchemaName};

CREATE TABLE achievements
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_achievements PRIMARY KEY (id)
);

CREATE TABLE media
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_file_name VARCHAR(255),
    size               BIGINT,
    media_type         VARCHAR(255),
    bytes              OID,
    CONSTRAINT pk_media PRIMARY KEY (id)
);

CREATE TABLE question_answers
(
    question_id BIGINT NOT NULL,
    answers     VARCHAR(255)
);

CREATE TABLE question_media
(
    media_id    BIGINT NOT NULL,
    question_id BIGINT NOT NULL
);

CREATE TABLE questions
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    right_answer VARCHAR(255),
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR(255),
    password          VARCHAR(255),
    email             VARCHAR(255),
    name              VARCHAR(255),
    surname           VARCHAR(255),
    registration_date date,
    avatar_id         BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_achievements
(
    user_id         BIGINT NOT NULL,
    achievements_id BIGINT NOT NULL
);

CREATE TABLE users_passed_tests
(
    user_id         BIGINT NOT NULL,
    passed_tests_id BIGINT NOT NULL
);


CREATE TABLE test_question
(
    question_id BIGINT NOT NULL,
    test_id     BIGINT NOT NULL
);

CREATE TABLE tests
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    previous_test_id BIGINT,
    CONSTRAINT pk_tests PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_avatar UNIQUE (avatar_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_AVATAR FOREIGN KEY (avatar_id) REFERENCES media (id);

ALTER TABLE question_media
    ADD CONSTRAINT fk_quemed_on_media FOREIGN KEY (media_id) REFERENCES media (id);

ALTER TABLE question_media
    ADD CONSTRAINT fk_quemed_on_question FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE question_answers
    ADD CONSTRAINT fk_question_answers_on_question FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE users_achievements
    ADD CONSTRAINT fk_useach_on_achievement FOREIGN KEY (achievements_id) REFERENCES achievements (id);

ALTER TABLE users_achievements
    ADD CONSTRAINT fk_useach_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_passed_tests
    ADD CONSTRAINT fk_usepastes_on_test FOREIGN KEY (passed_tests_id) REFERENCES tests (id);

ALTER TABLE users_passed_tests
    ADD CONSTRAINT fk_usepastes_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tests
    ADD CONSTRAINT FK_TESTS_ON_PREVIOUSTEST FOREIGN KEY (previous_test_id) REFERENCES tests (id);

ALTER TABLE test_question
    ADD CONSTRAINT fk_tesque_on_question FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE test_question
    ADD CONSTRAINT fk_tesque_on_test FOREIGN KEY (test_id) REFERENCES tests (id);